spring:
  application:
    name: job-tracker-backend

  datasource:
    url: jdbc:postgresql://localhost:5432/jobtrackerdb
    username: admin
    password: admin123
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

server:
  port: 8080
  servlet:
    context-path: /api

app:
  jwt:
    secret: "change_this_to_a_strong_secret"
    accessExpirationSeconds: 900
    refreshExpirationSeconds: 1209600